config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/upload',   to: 'static_pages#upload'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  get  '/search/:id',  to: 'users#search', as: 'search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets, only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  get '/auth/facebook/callback', to: 'sessions#create'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def upload
    @micropost = current_user.microposts.build
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<% provide(:title, "Search") %>
<div class="row">
  <div class="col-md-8">
    <p>micropost serch</p>
    <%= form_tag user_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Insta Clone</h1>
    <h2>下項目からログイン方法を選んでください</h2>
    <div class="lp">
      <img src="/assets/iphone02.jpg">
      <div class="first">初めての方はこちら</div>
      <div class="sign-up"><%= link_to "新規アカウント作成", signup_path, class: "btn btn-lg btn-primary" %></div>
      <div class="second">ログインはこちら</div>
      <div class="login"><%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %></div>
      <div class="facebook-login">facebookログインはこちら</div>
      <p>
        <%= link_to '/auth/facebook', class: "btn btn-social btn-facebook" do %>
          <span class="fa fa-facebook"></span> Facebookアカウントでログイン
        <% end %>
      </p>
    </div>
  </div>
<% end %>

app/views/static_pages/upload.html.erb
<% provide(:title, "upload") %>
<div class="upload">
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, multiplu: true, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>
</div>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>