config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/upload',   to: 'static_pages#upload'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  get  '/search/:id',  to: 'users#search', as: 'search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets, only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  get '/auth/facebook/callback', to: 'sessions#create'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def edit
  end
  
  def update
    user = current_user
    password = params[:password_resets][:password]
    reset = params[:password_resets][:reset]
    reset_confirmation = params[:password_resets][:reset_confirmation]
    if password.empty? || reset.empty? || reset_confirmation.empty?
      flash.now[:gender] = "password or new_password not alive"
      render 'edit'
    elsif !(reset == reset_confirmation)
      flash.now[:gender] = "new_password not match confirmation"
      render 'edit'
    elsif user && user.authenticate(params[:password_resets][:password])
      user.update(password: params[:password_resets][:reset],password_confirmation: params[:password_resets][:reset_confirmation])
      flash[:success] = "Password has been reset."
      redirect_to user
    else
      flash.now[:gender] = "password missmatch"
      render 'edit'
    end
  end
  
  private
  
  def password_params
    params.require(:password_resets).permit(:password, :reset,
                                            :reset_confirmation)
  end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Forgot password") %>
<h1>password reset</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_resets, url: password_reset_path, html: {method: "patch"}) do |f| %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :new_password %>
      <%= f.password_field :reset, class: 'form-control' %>
      
      <%= f.label :new_password_confirmation %>
      <%= f.password_field :reset_confirmation, class: 'form-control' %>
      
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>